version: "3"
services:
  client-front:
    image: "node:16-alpine"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ../:/home/node/app
      - ./node_modules:/app/node_modules/
    command: >
      sh -c "
      yarn install &&
      yarn build:prod && yarn start:prod"

    networks:
      - infrastructure_backend


networks:
  infrastructure_backend:
    external: true
